# Generated by Django 6.0.2 on 2026-03-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.AddField(
            model_name='service',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Controls display order in home page and sidebar (lower = first)'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, help_text="Font Awesome class string, e.g. 'fa-solid fa-file-invoice'", max_length=100),
        ),
        migrations.AddField(
            model_name='service',
            name='list_url_name',
            field=models.CharField(blank=True, help_text="Django URL name for this service's list page, e.g. 'reports:report_list'", max_length=200),
        ),
    ]
